fail_fast: true
repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
      - id: format-check
        name: format-check
        entry: make format-check
        language: system
        pass_filenames: false
        always_run: true
